### ISSUE TITLE
Questions about how the reward is used and how imitation learning is used in your paper

### ISSUE THREAD

**Issue by GoingMyWay** [daochenzha/rapid#3]
Dear Authors,

After reading your paper, I have a  question about how imitation learning is used in your paper. In your code (https://github.com/daochenzha/rapid/blob/HEAD/rapid/agent.py#L153), I found at the end of each episode, the agent's policy will be updated with imitation learning by using the good episodes. In https://github.com/daochenzha/rapid/blob/HEAD/rapid/agent.py#L272, the agent's model will be updated with RL. Is my understanding right? By the way, is imitation learning necessary and important for the improvement of the rewards? 

In Line 8, Algorithm 1, Give score S_{\tau} to all the state-action pairs in  \tau and store them into the buffer. Does it mean in this sparse reward setting, each timestep of this episode will be reassigned an identical reward?

**Comment by daochenzha** [comment]
@GoingMyWay Thanks for reading our paper!

Yes. Your understanding is correct. The imitation part is very important. If you try `--disable_rapid`, which will disable imitation learning, the performance will be very bad.

Yes, the same score will be assigned to all the state-action pairs in \tau. The score is given in the episode level to quantify the overall exploration behavior and we assume all the state-action pairs contribute equally. It is possible to achieve better performance if up-weighting some important state-action pairs (but I have not tried).

**Comment by GoingMyWay** [comment]
> @GoingMyWay Thanks for reading our paper!
> 
> Yes. Your understanding is correct. The imitation part is very important. If you try `--disable_rapid`, which will disable imitation learning, the performance will be very bad.
> 
> Yes, the same score will be assigned to all the state-action pairs in \tau. The score is given in the episode level to quantify the overall exploration behavior and we assume all the state-action pairs contribute equally. It is possible to achieve better performance if up-weighting some important state-action pairs (but I have not tried).

Thanks. Your answer enhanced my understanding.
